version: '3.5'

services:
  mysql:
    container_name: dbzabbix-mysql
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin  
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - zbxnet

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: srvzabbix
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    networks:
      - zbxnet

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbixweb-nginx
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - zbxnet

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    container_name: zabbixagent
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zbxnet
  
  zabbix-agent-mysql:
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    container_name: zabbix-agent-mysql
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: srvzabbix
      ZBX_HOSTNAME: dbzabbix-mysql
    volumes:
      - ./mysql.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/
    depends_on:
      - mysql  
    networks:
      - zbxnet
    
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - zbxnet        

networks:
  zbxnet: